name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: node --version
      - run: npm install
      - run: npm test

  test-old:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          . ~/.nvm/nvm.sh

          nvm install v0.10.48
          nvm use v0.10.48

          npm install
          npm test
